### ISSUE TITLE
Wrong encoding with non-ascii symbol sentences

### ISSUE THREAD

**Issue by VladChekunov** [raitucarp/superspin#1]
If you want to using non-ascii symbols in sentences, you will get wrong encoding. 

Already fixed that by changing 50 line of superspin.go:
`char := rune(sp.text[i])`
to
`char := runes[i]`
And adding variable runes before loop on line 49:
`runes := []rune(sp.text)`

**Comment by raitucarp** [comment]
Hi, thanks for your investigation and bug found, I will fix it soon. Or if you want to contribute with a PR, you're welcome, I would happy to merge it

**Comment by VladChekunov** [comment]
I was make pull request that fix that problem.

**Comment by raitucarp** [comment]
OK, LGTM, already merged. I'm sorry for slow response due to inactivity recently...
